[package]
name = "avatar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
nanoid = "0.4.0"
rand = "0.9.2"
rfd = "0.15.4"
sdl2 = {version="0.38.0", features=["ttf", "image", "gfx"]}
strum = { version = "0.27.2", features = ["derive"] }
