[package]
name = "avatar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy = {version="0.17.2"}
bevy_egui = "0.37.1"
nanoid = "0.4.0"
rand = "0.9.2"
rfd = "0.15.4"
strum = { version = "0.27.2", features = ["derive"] }
